name: Lint
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    name: Setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

  gofmt:
    runs-on: ubuntu-latest
    name: Gofmt
    needs: [setup]
    steps:
      - run: go fmt ./... | tee /dev/stderr | read && exit 1 || exit 0
      - run: go vet ./... | tee /dev/stderr | read && exit 1 || exit 0

  gosec:
    runs-on: ubuntu-latest
    name: Gosec
    needs: [setup]
    steps:
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: "-no-fail -fmt sarif -out results.sarif ./..."
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif

  golangci-lint:
    runs-on: ubuntu-latest
    name: Golangci-lint
    needs: [setup]
    steps:
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
